=== Calcul des ressources restantes d'une machine hôte

Nous allons effectuer le calcul des ressources restantes d'une machine hôte après avoir installé une machine virtuelle.

Voici les caractéristiques d'une machine hôte et d'une machine virtuelle installée :

[WARNING]
.Rappels
====
* Les ressources d'une machine virtuelle sont définies lors de son installation.
* Les ressources attribuées à une machine virtuelle ne peuvent plus être attribuées à une autre machine virtuelle ou à la machine hôte.

====



|===
|Machine | RAM | CPU | Disque dur

|Machine hôte | 8 Go | 4 coeurs | 1 To

|Machine virtuelle | 2 Go | 2 coeurs | 20 Go

|===

*Question 1 :* Combien reste-t-il de ressources sur la machine hôte ?


Lors de la création d'une VM, les ressources allouées à la VM sont déduites des ressources de la machine hôte.

Pour calculer les ressources restantes, il faut soustraire les ressources de la VM aux ressources de la machine hôte.

* RAM : 8 Go - 2 Go = 6 Go
* CPU : 4 coeurs - 2 coeurs = 2 coeurs
* Disque dur : 1 To - 20 Go = 980 Go


*Question 2* : Combien de machines virtuelles de ce type peut-on installer sur la machine hôte ?

Pour répondre à cette question, il suffit de diviser les ressources restantes par les ressources de la VM.


*Question 3* : Puis-je installer une troisième machine virtuelle de ce type sur la machine hôte, et ne la démarrer que si les deux autres machines virtuelles sont arrêtées ?

Non, car les ressources allouées à une machine virtuelle ne peuvent pas être utilisées par une autre machine virtuelle ou par la machine hôte.

Nous sommes donc limités à deux machines virtuelles de ce type sur la machine hôte.







